name: flutter_nodejs_base
description: Flutter base project prepared to consume a Node.js backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  flutter_secure_storage: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
